build: false
platform:
  - x64
clone_folder: c:\projects\saving-iterator

environment:
  matrix:
    - php_ver_target: 8.0

init:
  - SET COMPOSER_NO_INTERACTION=1

## Install PHP and composer, and run the appropriate composer command
install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/ChadSikorra/ps-install-php/master/Install-PHP.ps1" -OutFile "Install-PHP.ps1"
  - ps: .\Install-PHP.ps1 -Version $Env:php_ver_target -Highest -Arch x64 -Extensions mbstring,intl,openssl,curl
  - rm .\Install-PHP.ps1
  - refreshenv
  - mkdir C:\composer
  - cd C:\composer
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - powershell -command "(Get-Item C:\composer\composer.phar).length"
  - powershell -command "'@php C:\composer\composer.phar ' + $([char]37) + '*' | Out-File C:\composer\composer.bat -Encoding ASCII"
  - SET PATH=C:\composer;%PATH%
  - cd c:\projects\saving-iterator
  - composer install --no-progress --profile

## Run the actual test
test_script:
  - cd c:\projects\saving-iterator
  # PHPUnit tests
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml
  # Coverage files
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml
  # Coverage check
  - vendor/bin/coverage-check coverage.xml 100 --only-percentage
  # PHPStan analysis
  - ./vendor/bin/phpstan analyse