environment:
  # Use this matrix as an example
  matrix:

    # Specify matrix item for your app
    - PHP_VERSION: 8.0
      php_ver_target: 8.0
      VC_VERSION: 16 # was 15 before
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  PHP_AVM: https://raw.githubusercontent.com/sergeyklay/php-appveyor/master/php-appveyor.psm1

# Cache PHP and tooling
cache:
  # The C:\Downloads directory will be used as a storage for downloaded archives.
  # So you may want to cache it.
  - 'C:\Downloads -> .appveyor.yml'

# Specify required architecture.
# Supported architectures are ``x86`` and ``x64``
platform:
  - x64

install:
  # Download php-appveyor.psm1 module and invoke it to the current session
  - ps: (new-object Net.WebClient).DownloadString($Env:PHP_AVM) | iex
  - ps: InstallPhp        $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallPhpDevPack $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM

#build_script:
  # Your code here
#--------------------------------
build: false

clone_folder: c:\projects\saving-iterator

init:
  - SET COMPOSER_NO_INTERACTION=1

## Install PHP and composer, and run the appropriate composer command
#install:

## Run the actual test
test_script:
  - cd c:\projects\saving-iterator
  # PHPUnit tests
  - vendor\bin\phpunit --coverage-text --configuration phpunit.xml
  # Coverage files
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml
  # Coverage check
  - vendor/bin/coverage-check coverage.xml 100 --only-percentage
  # PHPStan analysis
  - ./vendor/bin/phpstan analyse