architect:
  - MaxGoryunov
install:
  - "sudo apt-get update"
  - "sudo apt install -y php8.0-dom"
  - "sudo apt install -y curl"
  - "sudo apt-get install -y php8.0-mbstring"
  - "sudo apt-get install -y php-xdebug"
  - "composer install"
merge:
  script:
    - "./vendor/bin/phpunit --bootstrap=vendor/autoload.php --coverage-text"
    - "XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4"
    - "./vendor/bin/phpstan analyse"
release:
  script:
    - "./vendor/bin/phpunit --bootstrap=vendor/autoload.php --coverage-text"
    - "XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4"
    - "./vendor/bin/phpstan analyse"