architect:
  - MaxGoryunov
install:
  - "sudo apt install php-xml"
  - "Y"
  - "composer install"
merge:
  script:
    - "./vendor/bin/phpunit --bootstrap=vendor/autoload.php --coverage-text"
    - "XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4"
    - "./vendor/bin/phpstan analyse"
release:
  script:
    - "./vendor/bin/phpunit --bootstrap=vendor/autoload.php --coverage-text"
    - "XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4"
    - "./vendor/bin/phpstan analyse"