language: php
php:
  - '8.0'
install:
  - composer install
script:
  # PHPUnit tests
  - vendor/bin/phpunit --coverage-text --configuration phpunit.xml
  # Infection analysis
  - XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=90 --min-covered-msi=90 --threads=4 --configuration=./infection.json.dist
  # Coverage files
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml
  # Coverage check
  - vendor/bin/coverage-check coverage.xml 100 --only-percentage
  # PHPStan analysis
  - ./vendor/bin/phpstan analyse
after_script:
  - bash <(curl -s https://codecov.io/bash)