codecov:
  require_ci_to_pass: yes
  token: c45f6f02-e5d7-4ee5-8b50-78744fe2bf77
coverage:
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: 100%
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no