name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: Set up autoload
      run: composer dump-autoload

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        TEST_NAME: AllTests
      with:
        bootstrap: vendor/autoload.php
        configuration: ./phpunit.xml
        args: --coverage-text