name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v2
      env:
        TEST_NAME: AllTests
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        args: --coverage-text
# @todo #45:30min The minimum required MSI percentage should be 80%, but actual
#  is 70%.
    - name: Infection analysis
      run: XDEBUG_MODE=coverage ./vendor/bin/infection --min-msi=65 --min-covered-msi=80 --threads=4 --configuration=./infection.json.dist

    - name: Create PHPUnit coverage files
      run: "XDEBUG_MODE=coverage  ./vendor/bin/phpunit --coverage-clover=coverage.xml"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: tests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: PHPStan analysis
      run: ./vendor/bin/phpstan analyse