name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v2
      env:
        TEST_NAME: AllTests
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        args: --coverage-text
  
    - name: Create PHPUnit coverage files
      run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: tests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: PHPStan analysis
      run: ./vendor/bin/phpstan analyse

    - name: Infection analysis
      run: ./vendor/bin/infection --min-msi=80 --min-covered-msi=80 --threads=4